version: '3.1'
services:
  stats-server:
    build: ./stats/stats-server
    image: stats_server_image
    container_name: stats-server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - JAVA_OPTS=-Dserver.port=9090
#      - TZ=Europe/Moscow
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats
      - DB_USER=test
      - DB_PASSWORD=test
  stats-db:
    image: postgres:14-alpine
    container_name: stats-db
    ports:
      - "6541:5432"
    volumes:
      - /var/lib/postgresql/data-stats/
    environment:
      - POSTGRES_DB=stats
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
  ewm-service:
    build: ./ewm-service
    image: ewm_service_image
    container_name: ewm-service
    ports:
      - "8080:8080"
    depends_on:
      - stats-server
      - ewm-db
    environment:
      - JAVA_OPTS=-Dserver.port=8080
#      - TZ=Europe/Moscow
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewm
      - STATS_SERVER_URL=http://stats-server:9090
      - DB_USER=test
      - DB_PASSWORD=test
  ewm-db:
    image: postgres:14-alpine
    container_name: ewm-db
    ports:
      - "6540:5432"
    volumes:
      - /var/lib/postgresql/data-ewm/
    environment:
      - POSTGRES_DB=ewm
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
